In [2]:
import numpy as np

In [6]:
a = np.array([[10,20,30,40], [50,60,70,80]])
print(a.shape)
print(a.ndim)

(2, 4)
2


In [10]:
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
               [[11,12,13,14],
                [15,16,17,18],
                [19,20,21,22]]])
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [12]:
a = np.array([1,2,3,4,5])
print(a[2])
print(a[-1])

3
5


In [14]:
a = np.array([[0,1,2], [3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [15]:
print(a[0,0])

0


In [18]:
print(a[0][0])
print(a[0,1]) #첫 번째 행의 두 번째 열

0
1


In [19]:
a = np.array([[0,1,2,3],
              [4,5,6,7]])

print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [26]:
print(a[0,:])
print(a[:,0:2])
print(a[:,1])
print(a[1,1:])
print(a[:2,:2])

[0 1 2 3]
[[0 1]
 [4 5]]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [48]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

print(m[1,2])
print(m[2,4])
print(m[1,1:3])
print(m[1:,2])
print(m[0:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [52]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a % 2)
print(a % 2 == 0)
print(a[a%2 == 0])

[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [62]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20]])

print(a[a % 3== 0])
print(a[a % 4 == 1])
print(a[(a%3==0) & (a%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [65]:
x = np.array([1.0,2.0,3.0])
print(x.dtype)
print(x[0], x[1], x[2])

float64
1.0 2.0 3.0


In [69]:
a = np.zeros(5)
b = np.ones(5)
c = np.empty(4)

print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.01106037e-307]


In [70]:
a1 = np.arange(10)
a2 = np.arange(3,21,2)
a3 = np.linspace(0,100,11)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13 15 17 19]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [78]:
x = np.array([10,20,30,40])
y = np.array([21,49,68,80])
x_mean = np.mean(x)
y_mean = np.mean(y)

#기울기 계산
numerator = np.sum((x- x_mean)*(y-y_mean))
denominator = np.sum((x-x_mean)**2)

slope = numerator/denominator
print(slope)

#절편 계산
intercept = y_mean - slope * x_mean
print(intercept)

#광고비가 35만원인 경우 예측 판매량
y_predict = (slope*35) + intercept
print(y_predict)

1.96
5.5
74.1


In [85]:
import numpy as np

x = [1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0]
y = [0.2,0.3,0.5,0.6,0.9,0.95,1.1,1.5]

x_mean = np.mean(x)
y_mean = np.mean(y)

numerator = np.sum((x- x_mean)*(y-y_mean))
denominator = np.sum((x-x_mean)**2)

slope = numerator/denominator
intercept = y_mean - slope * x_mean

y_predict1 = (slope*15) + intercept
y_predict2 = (slope*22) + intercept
y_predict3 = (slope*100) + intercept

print(round(y_predict1,3), round(y_predict2,3), round(y_predict3,3))

z = y[4] - ((slope*5)+intercept)
print(round(z,3))


2.6 3.829 17.526
0.056
