In [ ]:
#XOR 연산, 은닉층 노드 4개로 수정

import numpy as np
import tensorflow as tf


X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
Y = np.array([[0], [1], [1], [0]])

seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#은닉층 가중치와 편향
W1 = tf.Variable(tf.random.normal([2, 4]), dtype=tf.float32)
b1 = tf.Variable(tf.random.normal([4]), dtype=tf.float32)
#출력층 가중치와 편향
W2 = tf.Variable(tf.random.normal([4, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random.normal([1]), dtype=tf.float32)

def hypothesis(X) :
    return 1 / (1+tf.exp(-X))

#다층 퍼셉트론 정의 (은닉층 -> 출력층)
def perceptron(X):
    hidden = hypothesis(tf.matmul(X, W1) + b1)
    return hypothesis(tf.matmul(hidden, W2)+b2)

def cost(y_true, y_pred):
    return tf.reduce_mean(-(y_true * tf.math.log(y_pred) 
                            + (1-y_true) * tf.math.log(1-y_pred)))

opt = tf.keras.optimizers.SGD(learning_rate=0.5)

def binary_output(X):
    return int(X.numpy()[0][0] > 0.5)

def accuracy(y_true, y_pred):
    correct_prediction = tf.equal(tf.cast(y_pred > 0.5, tf.float32), y_true)
    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

for i in range(2001):
    with tf.GradientTape() as tape:
        pred = perceptron(X)
        loss = cost(Y, pred)
    grads = tape.gradient(loss, [W1, W2 ,b1, b2])
    opt.apply_gradients(zip(grads, [W1, W2, b1, b2]))

    if i % 200 == 0:
        W1_val = np.squeeze(W1.numpy())
        b1_val = np.squeeze(b1.numpy())
        W2_val = np.squeeze(W2.numpy())
        b2_val = np.squeeze(b2.numpy())
        print(f"Step: {i}, Loss: {loss.numpy():.9f}")
        print(f"W1 = {W1_val}, b1 = {b1_val}")
        print(f"W2 = {W2_val}, b2 = {b2_val}")

print("\n--------예측결과------------")

for input_data in X:
    prediction = perceptron(np.array([input_data], dtype=np.float32))
    print(f"입력: {input_data.tolist()}, 예측(확률): {prediction.numpy()[0][0]:.4f}, 예측(이진): {binary_output(prediction)}")


predictions = perceptron(X)
acc = accuracy(Y, predictions)
print(f"정확도: {acc.numpy():.4f}")

Step: 0, Loss: 0.712668121
W1 = [[ 1.5259279   0.4228885  -0.41778985 -1.0409056 ]
 [-1.2278113   0.47111446 -0.00707672  1.1773635 ]], b1 = [ 1.0943089   0.19585472 -0.5199015   0.0753455 ]
W2 = [-1.8471785  -0.14824514 -0.8655966   0.80834836], b2 = 1.6416518688201904
Step: 200, Loss: 0.565130234
W1 = [[ 3.366287   0.5152288 -1.0107279 -1.0650086]
 [-2.9027903  0.4323591  0.2298503  0.9225815]], b1 = [ 2.074873    0.23201135 -0.39258254 -0.22400145]
W2 = [-2.8343554   0.41185853 -1.185973   -0.2645822 ], b2 = 2.404750347137451
Step: 400, Loss: 0.333876789
W1 = [[ 4.933127   1.492609  -1.387992  -1.5226012]
 [-4.446143   0.4880445  1.5304215  2.2215662]], b1 = [2.6177166  0.4866467  0.41733086 0.48651755]
W2 = [-4.3446426  2.0461428 -1.9145958 -1.8990687], b2 = 3.9828298091888428
Step: 600, Loss: 0.117280766
W1 = [[ 5.8023825  2.3540971 -2.245574  -2.6285343]
 [-5.296762   1.6095005  3.0091846  3.5969229]], b1 = [2.8236759  0.43904606 1.0279282  1.1480671 ]
W2 = [-5.8501134  3.815555 

In [1]:
#XOR 연산, 은닉층을 2개 만들기

import numpy as np
import tensorflow as tf


X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
Y = np.array([[0], [1], [1], [0]])

seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#은닉층1 가중치와 편향
W1 = tf.Variable(tf.random.normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random.normal([2]), dtype=tf.float32)
#은닉층2 가중치와 편향
W2 = tf.Variable(tf.random.normal([2, 2]), dtype=tf.float32)
b2 = tf.Variable(tf.random.normal([2]), dtype=tf.float32)
#출력층 가중치와 편향
W3 = tf.Variable(tf.random.normal([2, 1]), dtype=tf.float32)
b3 = tf.Variable(tf.random.normal([1]), dtype=tf.float32)


def hypothesis(X) :
    return 1 / (1+tf.exp(-X))

#다층 퍼셉트론 정의 (은닉층1 -> 은닉층2 -> 출력층)
def perceptron(X):
    hidden1 = hypothesis(tf.matmul(X, W1) + b1)
    hidden2 = hypothesis(tf.matmul(hidden1, W2) + b2)
    return hypothesis(tf.matmul(hidden2, W3)+b3)

def cost(y_true, y_pred):
    return tf.reduce_mean(-(y_true * tf.math.log(y_pred) 
                            + (1-y_true) * tf.math.log(1-y_pred)))

opt = tf.keras.optimizers.SGD(learning_rate=0.5)

def binary_output(X):
    return int(X.numpy()[0][0] > 0.5)

def accuracy(y_true, y_pred):
    correct_prediction = tf.equal(tf.cast(y_pred > 0.5, tf.float32), y_true)
    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

for i in range(2000):
    with tf.GradientTape() as tape:
        pred = perceptron(X)
        loss = cost(Y, pred)
    grads = tape.gradient(loss, [W1, W2, W3, b1, b2, b3])
    opt.apply_gradients(zip(grads, [W1, W2, W3, b1, b2, b3]))

    if i % 200 == 0:
        W1_val = np.squeeze(W1.numpy())
        b1_val = np.squeeze(b1.numpy())
        W2_val = np.squeeze(W2.numpy())
        b2_val = np.squeeze(b2.numpy())
        W3_val = np.squeeze(W3.numpy())
        b3_val = np.squeeze(b3.numpy())
        print(f"Step: {i}, Loss: {loss.numpy():.9f}")
        print(f"W1 = {W1_val}, b1 = {b1_val}")
        print(f"W2 = {W2_val}, b2 = {b2_val}")
        print(f"W2 = {W3_val}, b2 = {b3_val}")

print("\n--------예측결과------------")

for input_data in X:
    prediction = perceptron(np.array([input_data], dtype=np.float32))
    print(f"입력: {input_data.tolist()}, 예측(확률): {prediction.numpy()[0][0]:.4f}, 예측(이진): {binary_output(prediction)}")


predictions = perceptron(X)
acc = accuracy(Y, predictions)
print(f"정확도: {acc.numpy():.4f}")

Step: 0, Loss: 0.720902681
W1 = [[ 1.5141771  0.4223039]
 [-0.4219279 -1.0374224]], b1 = [1.0743409  0.19206275]
W2 = [[-1.8266208  -0.14227036]
 [-0.85801953  0.8321797 ]], b2 = [ 1.6724098  -0.80997956]
W2 = [1.5858448 2.42529  ], b2 = -1.2378679513931274
Step: 200, Loss: 0.601834297
W1 = [[ 2.4873042   0.82873034]
 [-2.1199348  -1.3795568 ]], b1 = [1.287864  0.1524253]
W2 = [[-3.1142797 -0.6723863]
 [-1.2604715  1.3137043]], b2 = [ 1.3541964  -0.72616297]
W2 = [2.525672  2.6297338], b2 = -1.4746224880218506
Step: 400, Loss: 0.232362583
W1 = [[ 3.9111397  2.6055896]
 [-3.6704617 -3.092086 ]], b1 = [ 1.9375429 -1.1609306]
W2 = [[-4.9723697 -1.5756695]
 [-1.6981571  4.0928154]], b2 = [ 1.7738936  -0.69160736]
W2 = [4.406598 4.734508], b2 = -2.549131393432617
Step: 600, Loss: 0.063337490
W1 = [[ 4.4873834  3.6419568]
 [-4.34496   -3.9732778]], b1 = [ 2.1680522 -1.8878458]
W2 = [[-5.7476683 -2.58152  ]
 [-1.7696525  5.78902  ]], b2 = [ 2.090412   -0.40089864]
W2 = [5.460013 7.010359], b2

폐암 수술 환자의 생존율 예측
- Hidden layer 1개 (노드 30개)
- hidden layer와 hypothesis 모두 sigmoid

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt("Data/ThoraricSurgery.csv", delimiter=',')

x_train = data[:, 0:17].astype(np.float32)
y_train = data[:, [17]].astype(np.float32)

seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

W1 = tf.Variable(tf.random.normal([17,30]), name = 'W1')
b1 = tf.Variable(tf.random.normal([30]), name = 'b1')
W2 = tf.Variable(tf.random.normal([30,1]), name = 'W2')
b2 = tf.Variable(tf.random.normal([1]), name = 'b2')


def forward(x):
    hidden = tf.sigmoid(tf.matmul(x, W1) + b1)
    hypothesis = tf.sigmoid(tf.matmul(hidden, W2) + b2)
    return hypothesis

def cost(y_true, y_pred):
    return tf.reduce_mean(-(y_true * tf.math.log(y_pred) 
                            + (1-y_true) * tf.math.log(1-y_pred)))

opt = tf.keras.optimizers.SGD(learning_rate=0.1)

def binary_output(X):
    return int(X.numpy()[0][0] > 0.5)

def accuracy(y_true, y_pred):
    correct_prediction = tf.equal(tf.cast(y_pred > 0.5, tf.float32), y_true)
    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

for i in range(2001):
    with tf.GradientTape() as tape:
        pred = forward(x_train)
        loss = cost(y_train, pred)
    grads = tape.gradient(loss, [W1, W2, b1, b2])
    opt.apply_gradients(zip(grads, [W1, W2, b1, b2]))

    if i % 200 == 0:
        print(f"Step: {i}, Loss: {loss.numpy():.9f}")
       

print("\n--------예측결과------------")

for input_data in x_train:
    prediction = forward(np.array([input_data], dtype=np.float32))
    print(f"입력: {input_data.tolist()}, 예측(확률): {prediction.numpy()[0][0]:.4f}, 예측(이진): {binary_output(prediction)}")


predictions = forward(x_train)
acc = accuracy(y_train, predictions)
print(f"정확도: {acc.numpy():.4f}")



Step: 0, Loss: 1.835230112
Step: 200, Loss: 0.424047410
Step: 400, Loss: 0.420239329
Step: 600, Loss: 0.416814566
Step: 800, Loss: 0.414560705
Step: 1000, Loss: 0.412819773
Step: 1200, Loss: 0.411377609
Step: 1400, Loss: 0.410145670
Step: 1600, Loss: 0.409068406
Step: 1800, Loss: 0.407960773
Step: 2000, Loss: 0.407052189

--------예측결과------------
입력: [293.0, 1.0, 3.799999952316284, 2.799999952316284, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 1.0, 0.0, 62.0], 예측(확률): 0.1326, 예측(이진): 0
입력: [1.0, 2.0, 2.880000114440918, 2.1600000858306885, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 14.0, 0.0, 0.0, 0.0, 1.0, 0.0, 60.0], 예측(확률): 0.1758, 예측(이진): 0
입력: [8.0, 2.0, 3.190000057220459, 2.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 11.0, 0.0, 0.0, 1.0, 1.0, 0.0, 66.0], 예측(확률): 0.3978, 예측(이진): 0
입력: [14.0, 2.0, 3.9800000190734863, 3.059999942779541, 2.0, 0.0, 0.0, 0.0, 1.0, 1.0, 14.0, 0.0, 0.0, 0.0, 1.0, 0.0, 80.0], 예측(확률): 0.3403, 예측(이진): 0
입력: [17.0, 2.0, 2.2100000381469727, 1.8799999952316284, 0.0, 0.0, 1.0, 0

In [4]:
new_data = np.array([[132,2,2.12,1.72,1,0,0,0,0,0,12,0,0,0,1,0,74]], dtype=np.float32)

new_prediction = forward(new_data)
new_prediction_class = tf.cast(new_prediction > 0.5, dtype=tf.float32)

print(f"New Prediction:{new_prediction.numpy()}")
print(f"New Prediction class:{new_prediction_class.numpy()}")

New Prediction:[[0.21759139]]
New Prediction class:[[0.]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
import numpy as np
import tensorflow as tf

seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

Data = np.loadtxt("Data/ThoraricSurgery.csv", delimiter=',')

X = Data[:, 0:17].astype(np.float32)
Y = Data[:, [17]].astype(np.float32)

model = Sequential()
model.add(Input(shape = (17,)))
model.add(Dense(30, activation = 'sigmoid'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=  ['accuracy'])
model.fit(X,Y, epochs=30, batch_size=10)

print("\nAccuracy: %.4f" % (model.evaluate(X, Y)[1]))

input_data = np.array([[132,2,2.12,1.72,1,0,0,0,0,0,12,0,0,0,1,0,74]], dtype=np.float32)

prediction = model.predict(input_data)
print(prediction)

Epoch 1/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6532 - loss: 0.6280 
Epoch 2/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8511 - loss: 0.4712
Epoch 3/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8511 - loss: 0.4308
Epoch 4/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4260
Epoch 5/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4240
Epoch 6/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4225
Epoch 7/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4215
Epoch 8/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4208
Epoch 9/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4203
Epoch 10/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4199
Epoch 11/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8511 - loss: 0.4196
Epoch 12/30
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8511 - l

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
import numpy as np
import tensorflow as tf

seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
Y = np.array([[0], [1], [1], [0]], dtype=np.float32)

model = Sequential()
model.add(Input(shape = (2, )))
model.add(Dense(4, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=  ['binary_accuracy'])
model.fit(X,Y, epochs=1000, verbose = 2)

print("\nAccuracy: %.4f" % (model.evaluate(X, Y)[1]))

print('\n[예측 결과]')
print(model.predict(X))

Epoch 1/1000
1/1 - 1s - 848ms/step - binary_accuracy: 0.7500 - loss: 0.6402
Epoch 2/1000
1/1 - 0s - 47ms/step - binary_accuracy: 0.5000 - loss: 0.6397
Epoch 3/1000
1/1 - 0s - 44ms/step - binary_accuracy: 0.5000 - loss: 0.6392
Epoch 4/1000
1/1 - 0s - 47ms/step - binary_accuracy: 0.5000 - loss: 0.6387
Epoch 5/1000
1/1 - 0s - 48ms/step - binary_accuracy: 0.5000 - loss: 0.6381
Epoch 6/1000
1/1 - 0s - 53ms/step - binary_accuracy: 0.5000 - loss: 0.6376
Epoch 7/1000
1/1 - 0s - 107ms/step - binary_accuracy: 0.5000 - loss: 0.6371
Epoch 8/1000
1/1 - 0s - 61ms/step - binary_accuracy: 0.5000 - loss: 0.6367
Epoch 9/1000
1/1 - 0s - 55ms/step - binary_accuracy: 0.5000 - loss: 0.6362
Epoch 10/1000
1/1 - 0s - 55ms/step - binary_accuracy: 0.5000 - loss: 0.6357
Epoch 11/1000
1/1 - 0s - 52ms/step - binary_accuracy: 0.5000 - loss: 0.6352
Epoch 12/1000
1/1 - 0s - 55ms/step - binary_accuracy: 0.5000 - loss: 0.6347
Epoch 13/1000
1/1 - 0s - 60ms/step - binary_accuracy: 0.5000 - loss: 0.6342
Epoch 14/1000
1/1 -